import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Terms of Service | JCAL.ai',
  description: 'Terms of Service for JCAL.ai - AI-Powered No-Code App Builder by Innovix Dynamix',
};

export default function TermsOfServicePage() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-purple-900 via-blue-900 to-slate-900">
      <div className="container mx-auto px-4 py-16">
        <div className="max-w-4xl mx-auto bg-white/10 backdrop-blur-sm rounded-2xl p-8 border border-white/20">
          <h1 className="text-4xl font-bold text-white mb-8">Terms of Service</h1>
          
          <div className="prose prose-lg prose-invert max-w-none">
            <p className="text-gray-300 mb-6">
              <strong>Last updated:</strong> October 24, 2024
            </p>

            <h2 className="text-2xl font-semibold text-purple-400 mt-8 mb-4">1. Acceptance of Terms</h2>
            <p className="text-gray-300 mb-6">
              By accessing and using JCAL.ai ("the Platform"), you accept and agree to be bound by the terms and provision of this agreement. If you do not agree to abide by the above, please do not use this service.
            </p>

            <h2 className="text-2xl font-semibold text-purple-400 mt-8 mb-4">2. Description of Service</h2>
            <p className="text-gray-300 mb-6">
              JCAL.ai is an AI-powered no-code application building platform developed by Innovix Dynamix. The Platform allows users to create, build, and deploy applications using artificial intelligence assistance without requiring traditional coding knowledge.
            </p>

            <h2 className="text-2xl font-semibold text-purple-400 mt-8 mb-4">3. User Accounts</h2>
            <ul className="text-gray-300 mb-6 list-disc pl-6">
              <li>You must provide accurate and complete information when creating an account</li>
              <li>You are responsible for maintaining the security of your account credentials</li>
              <li>You must notify us immediately of any unauthorized use of your account</li>
              <li>One person or entity may not maintain multiple accounts</li>
            </ul>

            <h2 className="text-2xl font-semibold text-purple-400 mt-8 mb-4">4. Acceptable Use</h2>
            <p className="text-gray-300 mb-6">You agree not to use the Platform to:</p>
            <ul className="text-gray-300 mb-6 list-disc pl-6">
              <li>Create applications that violate any laws or regulations</li>
              <li>Develop malicious software or engage in harmful activities</li>
              <li>Infringe on intellectual property rights of others</li>
              <li>Attempt to reverse engineer or compromise the Platform</li>
              <li>Use the service for any unlawful or prohibited purpose</li>
            </ul>

            <h2 className="text-2xl font-semibold text-purple-400 mt-8 mb-4">5. Intellectual Property</h2>
            <p className="text-gray-300 mb-6">
              You retain ownership of applications and content you create using the Platform. By using our service, you grant us a limited license to host, store, and process your content as necessary to provide the service.
            </p>

            <h2 className="text-2xl font-semibold text-purple-400 mt-8 mb-4">6. AI-Generated Content</h2>
            <p className="text-gray-300 mb-6">
              Content generated by our AI systems is provided as-is. While we strive for accuracy, we do not guarantee the correctness, completeness, or suitability of AI-generated content for your specific needs.
            </p>

            <h2 className="text-2xl font-semibold text-purple-400 mt-8 mb-4">7. Payment Terms</h2>
            <ul className="text-gray-300 mb-6 list-disc pl-6">
              <li>Subscription fees are billed in advance on a recurring basis</li>
              <li>All fees are non-refundable unless otherwise specified</li>
              <li>We reserve the right to change pricing with 30 days notice</li>
              <li>Failure to pay may result in service suspension</li>
            </ul>

            <h2 className="text-2xl font-semibold text-purple-400 mt-8 mb-4">8. Service Availability</h2>
            <p className="text-gray-300 mb-6">
              We strive to maintain high service availability but do not guarantee uninterrupted access. We may perform maintenance, updates, or modifications that temporarily affect service availability.
            </p>

            <h2 className="text-2xl font-semibold text-purple-400 mt-8 mb-4">9. Limitation of Liability</h2>
            <p className="text-gray-300 mb-6">
              To the maximum extent permitted by law, Innovix Dynamix shall not be liable for any indirect, incidental, special, consequential, or punitive damages resulting from your use of the Platform.
            </p>

            <h2 className="text-2xl font-semibold text-purple-400 mt-8 mb-4">10. Termination</h2>
            <p className="text-gray-300 mb-6">
              Either party may terminate this agreement at any time. Upon termination, your access to the Platform will cease, and we may delete your account and associated data after a reasonable period.
            </p>

            <h2 className="text-2xl font-semibold text-purple-400 mt-8 mb-4">11. Changes to Terms</h2>
            <p className="text-gray-300 mb-6">
              We reserve the right to modify these terms at any time. We will notify users of material changes via email or platform notification. Continued use of the service constitutes acceptance of modified terms.
            </p>

            <h2 className="text-2xl font-semibold text-purple-400 mt-8 mb-4">12. Contact Information</h2>
            <p className="text-gray-300 mb-6">
              For questions about these Terms of Service, please contact us at:
            </p>
            <div className="bg-gray-800/50 rounded-lg p-4 mb-6">
              <p className="text-gray-300">
                <strong>Innovix Dynamix</strong><br />
                Email: legal@innovixdynamix.com<br />
                Website: https://innovixdynamix.com
              </p>
            </div>

            <p className="text-gray-300 text-sm">
              These Terms of Service are governed by the laws of the United States and are effective as of the date listed above.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}